version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 10380:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  # php:
  #   build:
  #     context: ./docker/php
  #     args:
  #       DOCKER_UID: ${DOCKER_UID:-1000}
  #   volumes:
  #     - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  #     - ./html:/var/www/html
  #   environment:
  #     DEV_KEY: HOGEhogeHOGEhogeHOGEhogeHOGEhoge
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
  mysql:
    build: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 10381:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
